#!/bin/sh
# /usr/bin/i3exit

# with openrc use loginctl
[[ $(cat /proc/1/comm) == "systemd" ]] && logind=systemctl || logind=loginctl

case "$1" in
    lock)
        ~/.scripts/blurlock
        ;;
    logout)
        i3-msg '[class="."] kill'
        i3-msg exit
        ;;
    suspend)
        ~/.scripts/blurlock && $logind suspend
        ;;
    hibernate)
        ~/.scripts/blurlock && $logind hibernate
        ;;
    reboot)
        i3-msg '[class="."] kill'
        $logind reboot
        ;;
    shutdown)
        i3-msg '[class="."] kill'
        $logind poweroff
        ;;
    *)
        echo "== ! i3exit: missing or invalid argument ! =="
        echo "Try again with: lock | logout | suspend | hibernate | reboot | shutdown"
        exit 2
esac

exit 0

